[config]
schemaVersion = "0.0.1"


[package]
namespace = "adamant"
name = "ModpackFramework"
versionNumber = "1.1.0"
description = "Reusable modpack framework: discovery, hash, HUD, and UI. Used by modpack coordinators."
websiteUrl = "https://github.com/h2-modpack/adamant-ModpackFramework"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-ModUtil = "4.0.1"
adamant-ModpackLib = "1.0.0"


[build]
icon = "./icon.png"
readme = "./THUNDERSTORE_README.md"
outdir = "./build"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "modpacks", ]
